### ISSUE TITLE
all icons should be PureComponent

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-vault-front#57]
for better perf, svg can be quite nested

and probably we can simplify bunch of the SVGs code. like no need to do `<g><g><path/></g></g>` , no need for `<title>`, no need for ` xmlns="http://www.w3.org/2000/svg"` neither

**Comment by flocks** [comment]
I think svg icons are already defined as stateless functional component. What's the point of turning them into `PureComponent` ?

**Comment by gre** [comment]
stateless function is not like PureComponent. function can't have a ref instance / internal state, but they are not treated as "pure" AFAIK, (like like a shallow equal shouldComponentUpdate implementation)

**Comment by gre** [comment]
nice explanation https://stackoverflow.com/a/40704083

> No way to manually control when a re-render is needed, since you can't define shouldComponentUpdate. A re-render happens every time the component receives new props (no way to shallow compare, etc.). In the future, React could automatically optimise stateless components, for now there's some libraries you can use. Since stateless components are just functions, basically it's the classic problem of "function memoization".

**Comment by gre** [comment]
TBH this issue is very minor and just some polish. but I think if you have like lot of icons AND lot of redraw happening somewhere, it is possible a deep nested icon to be a perf bottleneck (might be premature optim ;) )
